server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      fail-fast: true
      server:
        git:
          uri: git@github.com:debangshud/groodle-config.git
          default-label: main
          search-paths: src/main/resources
          basedir: file://${user.home}/config-repo
          cloneOnStart: true
          refreshRate: 60
          ignoreLocalSshSettings: true
          hostKey: AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          hostKeyAlgorithm: ssh-ed25519
          privateKey: |
                      -----BEGIN OPENSSH PRIVATE KEY-----
                      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
                      QyNTUxOQAAACCgm1/6FTliI0QBIn1wFzBlXDUfrQzoPx1d8oqqKLzSeAAAAKDRaI+f0WiP
                      nwAAAAtzc2gtZWQyNTUxOQAAACCgm1/6FTliI0QBIn1wFzBlXDUfrQzoPx1d8oqqKLzSeA
                      AAAEDqrlh5lLEGotJEyO6GSvknPXNGiEiHjRpRSdBY/Osj0qCbX/oVOWIjRAEifXAXMGVc
                      NR+tDOg/HV3yiqoovNJ4AAAAHGRlYmFuZ3NodS5kYXNndXB0YUBnbWFpbC5jb20B
                      -----END OPENSSH PRIVATE KEY-----