spring:
  application:
    name: oauth-service
  cloud:
    config:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
security:
  jwt:
    key-store: classpath:certs/keystore.jks
    key-store-password: changeit
    key-pair-alias: mytestkey
    key-pair-password: changeit