spring:
  application:
    name: product-service
  cloud:
    config:
      enabled: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,info,beans"
graphql:
  servlet:
    actuator-metrics: true
  playground:
    cdn:
      version: latest
altair:
  enabled: true
  cdn:
    enabled: false
graphiql:
  enabled: true
  cdn:
    enabled: true
    version: 0.17.5
voyager:
  enabled: true
  cdn:
    enabled: false
graphql.playground:
  enabled: true
  cdn:
    enabled: false