spring:
  application:
    name: api-gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/users/**
            - id: customer-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/customers/**
            - id: employee-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/employees/**
            - id: product-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/products/**
security:
  jwt:
    public-key: classpath:public.txt