server:
  port: 8085
spring:
  application:
    name: reference-service
  cloud:
    config:
      enabled: false
mongock:
  change-logs-scan-package: '[org.groodle.boot.service.reference.changelogs]'